const express=require('express')
const router=express.Router()
const userCtrl=require('../controllers/userController')
const protect=require('../middlewares/authMiddleware')
router.post('/register',userCtrl.register)
router.post('/login',userCtrl.login)
router.get('/data',protect,userCtrl.getUserById)
router.get('/resumes',protect,userCtrl.getAllResumes)
router.post('/send-otp', userCtrl.sendOtp)
router.post('/reset-password', userCtrl.resetPassword)
module.exports=router